# Generated by Django 2.0.13 on 2019-05-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_university_ciudad'),
        ('my_plan', '0002_costodevida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplan',
            name='program',
        ),
        migrations.AddField(
            model_name='myplan',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.Period'),
            preserve_default=False,
        ),
    ]
