# Generated by Django 2.0.13 on 2019-05-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_plan', '0003_auto_20190523_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Program'),
        ),
    ]
