# Generated by Django 2.0.13 on 2019-05-07 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_description', models.CharField(max_length=400)),
                ('prog_description', models.CharField(max_length=400)),
                ('uni_calification', models.FloatField(default=0.0)),
                ('prog_calification', models.FloatField(default=0.0)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
