# Generated by Django 2.0.13 on 2019-05-07 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prog_calification', models.FloatField(default=0.0)),
                ('study_program', models.FileField(blank=True, upload_to='documents/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.FloatField(default=0.0)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('times_higher_ed', models.CharField(default='No aplica', max_length=30)),
                ('web_link', models.URLField(blank=True)),
                ('city', models.CharField(default='What', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
        migrations.AddField(
            model_name='program',
            name='scholarships',
            field=models.ManyToManyField(blank=True, to='university.Scholarship'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
    ]
