# Generated by Django 2.0.13 on 2019-05-07 02:40

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
