# Generated by Django 2.0.13 on 2019-05-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190507_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='geolocation',
            new_name='geom',
        ),
    ]
