# Generated by Django 2.0.13 on 2019-05-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20190507_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='geom',
            new_name='geolocation',
        ),
    ]
