# Generated by Django 2.0.13 on 2019-05-08 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20190507_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('application_deadline', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='tipo',
            field=models.CharField(blank=True, choices=[('preg', 'pregrado'), ('pos', 'posgrado')], max_length=11),
        ),
        migrations.AddField(
            model_name='period',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Program'),
        ),
    ]
