# Generated by Django 2.0.13 on 2019-05-19 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20190508_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='application_startline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
