# Generated by Django 2.0.13 on 2019-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_period_application_startline'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='tipo',
            field=models.CharField(blank=True, choices=[('co', 'Colombia'), ('ec', 'Ecuador'), ('mx', 'Mexico'), ('ru', 'Rusia'), ('en', 'Inglaterra'), ('pe', 'Perú'), ('us', 'Estados Unidos'), ('ch', 'Chile'), ('ec', 'Ecuador')], max_length=15),
        ),
    ]
