# Generated by Django 2.0.13 on 2019-05-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_university_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='tipo',
            new_name='pais',
        ),
    ]
