# Generated by Django 2.0.13 on 2019-05-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20190520_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='pais',
            field=models.CharField(blank=True, choices=[('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Mexico', 'Mexico'), ('Rusia', 'Rusia'), ('Inglaterra', 'Inglaterra'), ('Perú', 'Perú'), ('Estados Unidos', 'Estados Unidos'), ('Chile', 'Chile'), ('Ecuador', 'Ecuador')], max_length=15),
        ),
    ]
