# Generated by Django 2.0.13 on 2019-05-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20190520_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='ciudad',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
