# Generated by Django 2.0.13 on 2019-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_university_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='pais',
            field=models.CharField(blank=True, choices=[('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Mexico', 'Mexico'), ('Rusia', 'Rusia'), ('Inglaterra', 'Inglaterra'), ('Perú', 'Perú'), ('Estados Unidos', 'Estados Unidos'), ('Chile', 'Chile')], max_length=15),
        ),
    ]
